api_platform:
    title: Test Task
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    defaults:
        route_prefix: '/api'
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    openapi:
        contact:
            name: 'Edvinas Puluikis'
            url: 'https://puluikis.lt'
            email: 'edvinas@puluikis.lt'
